definitions:
  models.Organization:
    properties:
      about:
        type: string
      addressLine:
        type: string
      availableIn:
        type: string
      bio:
        type: string
      categoriesIn:
        items:
          type: string
        type: array
      country:
        type: string
      district:
        type: string
      email:
        type: string
      experience:
        type: string
      id:
        type: integer
      imageUrl1:
        type: string
      imageUrl2:
        type: string
      imageUrl3:
        type: string
      name:
        type: string
      pageName:
        type: string
      phoneNo:
        type: string
      pinCode:
        type: string
      specialities:
        type: string
      state:
        type: string
    type: object
  models.ResponseUploadFile:
    properties:
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/organization:
    post:
      consumes:
      - application/json
      parameters:
      - description: Organization Data
        in: body
        name: organization
        required: true
        schema:
          $ref: '#/definitions/models.Organization'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new organization
      tags:
      - organizations
    put:
      consumes:
      - application/json
      parameters:
      - description: Organization Data
        in: body
        name: organization
        required: true
        schema:
          $ref: '#/definitions/models.Organization'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update organization details
      tags:
      - organizations
  /api/organization/{id}:
    get:
      parameters:
      - description: Organization ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get organization details by ID
      tags:
      - organizations
  /api/organizations:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Organization'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get list of all organizations
      tags:
      - organizations
  /api/upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseUploadFile'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Upload file to Amazon S3
      tags:
      - files
swagger: "2.0"
